version: "3.8"
services:
  api:
    ports:
      - "80:80"
    image: api:latest
    restart: unless-stopped
    depends_on:
      - meilisearch
    env_file:
      - .env
    environment:
      MEILISEARCH_URL: $MEILISEARCH_URL
      MEILISEARCH_API_KEY: $MEILISEARCH_API_KEY
    build:
      context: .
      dockerfile: Dockerfile
  meilisearch:
    image: getmeili/meilisearch:v0.24.0
    restart: unless-stopped
    user: root
    ports:
      - "7700:7700"
    volumes:
      - data-ms:/home/meili/data.ms
    environment:
      MEILI_MASTER_KEY: $MEILISEARCH_API_KEY
      MEILI_NO_ANALYTICS: "true"
      MEILI_ENV: "production"

volumes:
  data-ms:
