name: Testing

on:
  push:
    branches:
    - main
  pull_request:
jobs:
  linting:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: {% if cookiecutter.python_version[-1:] == "0" %}"{{ cookiecutter.python_version }}"{% else %}{{ cookiecutter.python_version }}{% endif %}
    - name: Get full Python version
      id: full-python-version
      run: echo ::set-output name=version::$(python -c "import sys; print('-'.join(str(v) for v in sys.version_info))")
    - name: Install Poetry and add to path
      run: |
        curl -sSL https://install.python-poetry.org/install-poetry.py | python -
        echo "${HOME}/.local/bin" >> $GITHUB_PATH
    - name: Configure poetry
      run: |
        poetry config virtualenvs.create true
        poetry config virtualenvs.in-project true
    - name: Cache poetry venv
      uses: actions/cache@v2
      id: poetry-cache
      with:
        path: .venv
        key: {{ "venv-${{ runner.os }}-${{ steps.full-python-version.outputs.version }}-${{ hashFiles('**/poetry.lock') }}" }}
        restore-keys: {{ "venv-${{ runner.os }}-poetry-" }}
    - name: Ensure cache is healthy
      if: steps.poetry-cache.outputs.cache-hit == 'true'
      shell: bash
      run: timeout 10s poetry run pip --version || rm -rf .venv
    - name: Install Dependencies
      run: poetry install
    - name: Isort check
      run: |
        poetry run isort app tests --check-only
    - name: Black check
      run: |
        poetry run black app tests --check
    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        poetry run flake8 app tests --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        poetry run flake8 app tests --count --exit-zero --max-complexity=10 --max-line-length={{ cookiecutter.max_line_length }} --statistics
    - name: mypy check
      run: |
        poetry run mypy .

  testing:
    strategy:
      fail-fast: false
      matrix:
        python-version: [{% for version in cookiecutter.python_version.split() %}{% if version.replace(",", "")[-1:] == "0" %}{% if version[-1:] == "," %}"{{ version }}" {% else %}"{{ version }}"{% endif %}{% else %}{% if version[-1:] == "," %}{{ version }} {% else %}{{ version }}{% endif %}{% endif %}{% endfor %}]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python {{ "${{ matrix.python-version }}" }}
      uses: actions/setup-python@v2
      with:
        python-version: {{ "${{ matrix.python-version }}" }}
    - name: Get full Python version
      id: full-python-version
      run: echo ::set-output name=version::$(python -c "import sys; print('-'.join(str(v) for v in sys.version_info))")
    - name: Install Poetry and add to path
      run: |
        curl -sSL https://install.python-poetry.org/install-poetry.py | python -
        echo "${HOME}/.local/bin" >> $GITHUB_PATH
    - name: Configure poetry
      run: |
        poetry config virtualenvs.create true
        poetry config virtualenvs.in-project true
    - name: Cache poetry venv
      uses: actions/cache@v2
      id: poetry-cache
      with:
        path: .venv
        key: {{ "venv-${{ runner.os }}-${{ steps.full-python-version.outputs.version }}-${{ hashFiles('**/poetry.lock') }}" }}
        restore-keys: {{ "venv-${{ runner.os }}-poetry-" }}
    - name: Ensure cache is healthy
      if: steps.poetry-cache.outputs.cache-hit == 'true'
      shell: bash
      run: timeout 10s poetry run pip --version || rm -rf .venv
    - name: Install Dependencies
      run: poetry install
    - name: Test with pytest
      run: |
        poetry run pytest
